blog/urls.py
from django.urls import path


from .views import category, post, tag

app_name = 'blog'


urlpatterns = [
    path('categories/<slug:slug>', category.index, name='category-index'),
    path('posts/<slug:slug>', post.DetailView.as_view(), name='post-detail'),
    path('tags/<slug:slug>', tag.index, name='tag-index'),
]

cleanblog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


from core.views import home


urlpatterns = [
    path('', home.index, name='home'),
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

core/urls.py
from django.urls import path


from .views.about import AboutView
from .views import contact

app_name = 'core'


urlpatterns = [
    path('about/', AboutView.as_view(), name='about'),
    path('contact/', contact.index, name='contact'),
]

blog/models/category.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True, max_length=255)
    description = models.TextField(null=True, blank=True)
    parent = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "categories"

blog/models/post.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.conf import settings
from django.db import models
from django.utils.safestring import mark_safe
from django.utils.translation import gettext_lazy as _

from .category import Category
from .tag import Tag


class Post(models.Model):
    title = models.CharField(max_length=255)
    subtitle = models.CharField(max_length=255)
    body = RichTextUploadingField()
    slug = models.SlugField(unique=True, max_length=255)
    background_image = models.ImageField(upload_to='posts/')
    categories = models.ManyToManyField(Category, related_name='posts')
    tags = models.ManyToManyField(Tag, related_name='posts')
    status = models.BooleanField()
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True,
                                   related_name='%(class)s_created_by')
    updated_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True,
                                   related_name='%(class)s_updated_by')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def background_image_tag(self):
        return mark_safe(
            '<a href="%s" target="_blank"><img src="/media/%s" width="150" /></a>'
            % (self.background_image.url, self.background_image)
        )

    background_image_tag.short_description = _('Background Image')

    def __str__(self):
        return self.title

blog/models/tag.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True, max_length=255)
    description = models.TextField(null=True, blank=True)
    parent = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

core/models/user.py
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

core/forms/contact_form.py
from django import forms
from django.utils.translation import gettext_lazy as _


class ContactForm(forms.Form):
    name = forms.CharField(label=_('Name'), label_suffix='', widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': _('Name')}
    ))
    email = forms.EmailField(label=_('Email Address'), label_suffix='', widget=forms.EmailInput(
        attrs={'class': 'form-control', 'placeholder': _('Email Address')}
    ))
    phone = forms.CharField(label=_('Phone Number'), label_suffix='', widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': _('Phone Number'), 'type': 'tel'}
    ))
    subject = forms.CharField(label=_('Subject'), label_suffix='', widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': _('Subject')}
    ))
    message = forms.CharField(label='Message', label_suffix='', widget=forms.Textarea(
        attrs={'class': 'form-control', 'placeholder': _('Message'), 'rows': 5}
    ))

blog/views/category.py
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, render


from ..models import Category


# List all posts for a category.
def index(request, slug):
    category = get_object_or_404(Category, slug=slug)
    post_list = category.posts.filter(status=1).order_by('-created_at')
    paginator = Paginator(post_list, 10)  # Show 10 posts per page.
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'taxonomy': category, 'page_obj': page_obj}
    return render(request, 'blog/taxonomy/index.html', context)

blog/views/post.py
from django.core.paginator import Paginator
from django.views import generic


from ..models import Post


# List posts on homepage.
def posts_for_homepage(request):
    post_list = Post.objects.filter(status=1).order_by('-created_at')
    paginator = Paginator(post_list, 4)  # Show 4 posts per page.
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return page_obj

# Generic detail view to show single post.
class DetailView(generic.DetailView):
    model = Post
    template_name = 'blog/post/detail.html'

blog/views/tag.py
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, render


from ..models import Tag


# List all posts for a tag.
def index(request, slug):
    tag = get_object_or_404(Tag, slug=slug)
    post_list = tag.posts.filter(status=1).order_by('-created_at')
    paginator = Paginator(post_list, 10)  # Show 10 posts per page.
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'taxonomy': tag, 'page_obj': page_obj}
    return render(request, 'blog/taxonomy/index.html', context)

core/views.py
from django.shortcuts import render

# Create your views here.

core/views/about.py
from django.views.generic import TemplateView


class AboutView(TemplateView):
    template_name = 'core/about.html'

core/views/contact.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.utils.translation import gettext_lazy as _


from ..forms import ContactForm
from core import signals


def index(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)

        if form.is_valid():
            contact = {
               'email': form.cleaned_data['email'],
               'message': form.cleaned_data['message'],
               'name': form.cleaned_data['name'],
               'phone': form.cleaned_data['phone'],
               'subject': form.cleaned_data['subject'],
            }

            signals.contact_request.send(sender='new_contact_request', contact=contact)

            messages.success(
                request,
                _('Thank you for your contact request. A member of our team will contact you within 24 hours.')
            )
    else:
        form = ContactForm()
    context = {'form': form}
    return render(request, 'core/contact.html', context)

core/views/home.py
from django.shortcuts import render


from blog.views.post import posts_for_homepage


def index(request):
    page_obj = posts_for_homepage(request)
    context = {'page_obj': page_obj}
    return render(request, 'core/index.html', context)

blog/templates/blog/post/detail.html
{% extends 'layout.html' %}

{% load i18n %}
{% load static %}

{% block title %}{{ post.title }}{% endblock %}

{% block body_class %}post-detail{% endblock %}

{% block hero_title %}{{ post.title }}{% endblock %}
{% block hero_subtitle %}{{ post.subtitle }}{% endblock %}
{% block hero_style %}style="background-image: url('{{ post.background_image.url }}')"{% endblock %}

{% block content %}
    <!-- Post Content-->
    <article class="mb-4">
        {% include 'blog/post/partials/_author_and_date_information.html' with author=post.created_by post_date=post.created_at|date:'j F, Y' %}

        {{ post.body|safe }}

        {% translate 'Categories' as taxonomy_category_title %}
        {% include 'blog/post/partials/_taxonomy_terms.html' with taxonomy_title=taxonomy_category_title taxonomy_term_url_name='blog:category-index' taxonomy_terms=post.categories.all %}

        {% translate 'Tags' as taxonomy_tag_title %}
        {% include 'blog/post/partials/_taxonomy_terms.html' with taxonomy_title=taxonomy_tag_title taxonomy_term_url_name='blog:tag-index' taxonomy_terms=post.tags.all %}
    </article>
{% endblock %}

blog/templates/blog/post/detail/_taxonomy_terms.html
<h3>{{ taxonomy_title }}</h3>
<ul class="list-inline taxonomy-terms-list">
    {% for taxonomy_term in taxonomy_terms %}
        <li class="list-inline-item">
            <span class="badge rounded-pill bg-dark">
                <a href="#" hreflang="en">{{ taxonomy_term.name }}</a>
            </span>
        </li>
    {% endfor %}
</ul>

blog/templates/blog/post/partials/_author_and_date_information.html
{% load i18n %}

{% if post.created_by %}
    {% blocktranslate %}
        Posted by {{ author }} on {{ post_date }}
    {% endblocktranslate %}
{% else %}
    {% blocktranslate %}
        Posted on {{ post_date }}
    {% endblocktranslate %}
{% endif %}

blog/templates/blog/post/partials/_preview.html
<!-- Post preview-->
<div class="post-preview">
    <a href="{% url 'blog:post-detail' post.slug %}">
        <h2 class="post-title">{{ post.title }}</h2>
        <h3 class="post-subtitle">
            {% autoescape off %}
                {{ post.body|truncatechars_html:150 }}
            {% endautoescape %}
        </h3>
    </a>
    <p class="post-meta">
        {% include 'blog/post/partials/_author_and_date_information.html' with author=post.created_by post_date=post.created_at|date:'j F, Y' %}
    </p>
</div>
<!-- Divider-->
<hr class="my-4" />

blog/templates/blog/post/partials/_taxonomy_terms.html
<h3>{{ taxonomy_title }}</h3>
<ul class="list-inline taxonomy-terms-list">
    {% for taxonomy_term in taxonomy_terms %}
        <li class="list-inline-item">
            <span class="badge rounded-pill bg-dark">
                <a href="{% url taxonomy_term_url_name taxonomy_term.slug %}" hreflang="en">{{ taxonomy_term.name }}</a>
            </span>
        </li>
    {% endfor %}
</ul>

blog/templates/blog/taxonomy/index.html
{% extends 'layout.html' %}

{% load i18n %}
{% load static %}

{% block title %}{{ taxonomy.name }}{% endblock %}

{% block hero_title %}{{ taxonomy.name }}{% endblock %}

{% block content %}
    {% for post in page_obj %}
        {% include 'blog/post/partials/_preview.html' with post=post %}
    {% empty %}
        <p>No posts found.</p>
    {% endfor %}

    {% include 'partials/_pagination.html' %}
{% endblock %}

core/templates/core/about.html
{% extends 'layout.html' %}

{% load i18n %}
{% load static %}

{% block title %}{% translate 'About Us' %}{% endblock %}

{% block hero_title %}{% translate 'About Us' %}{% endblock %}
{% block hero_subtitle %}{% translate 'This is what we do.' %}{% endblock %}
{% block hero_style %}style="background-image: url('{% static 'core/img/about-bg.jpg' %}')"{% endblock %}

{% block content %}
    {% blocktranslate trimmed %}
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
    {% endblocktranslate %}
{% endblock %}

core/templates/core/about/index.html
{% extends 'layout.html' %}

{% load i18n %}
{% load static %}

{% block title %}{% translate 'About Us' %}{% endblock %}

{% block hero_title %}{% translate 'About Us' %}{% endblock %}
{% block hero_subtitle %}{% translate 'This is what we do.' %}{% endblock %}
{% block hero_style %}style="background-image: url('{% static 'core/img/about-bg.jpg' %}')"{% endblock %}

{% block content %}
    {% blocktranslate trimmed %}
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
    {% endblocktranslate %}
{% endblock %}

core/templates/core/contact.html
{% extends 'layout.html' %}

{% load i18n %}
{% load static %}

{% block title %}{% translate 'Contact Us' %}{% endblock %}

{% block hero_title %}{% translate 'Contact Us' %}{% endblock %}
{% block hero_subtitle %}{% translate 'Have questions? We have answers.' %}{% endblock %}
{% block hero_style %}style="background-image: url('{% static 'core/img/contact-bg.jpg' %}')"{% endblock %}

{% block content %}
    {% blocktranslate trimmed %}
        <p>Want to get in touch? Fill out the form below to send me a message and I will get back to you as soon as possible!</p>
    {% endblocktranslate %}
    <div class="my-5">
        {% include 'core/contact/partials/_form.html' with form=form %}
    </div>
{% endblock %}

core/templates/core/contact/index.html
{% extends 'layout.html' %}

{% load i18n %}
{% load static %}

{% block title %}{% translate 'Contact Us' %}{% endblock %}

{% block hero_title %}{% translate 'Contact Us' %}{% endblock %}
{% block hero_subtitle %}{% translate 'Have questions? We have answers.' %}{% endblock %}
{% block hero_style %}style="background-image: url('{% static 'core/img/contact-bg.jpg' %}')"{% endblock %}

{% block content %}
    {% blocktranslate trimmed %}
        <p>Want to get in touch? Fill out the form below to send me a message and I will get back to you as soon as possible!</p>
    {% endblocktranslate %}
    <div class="my-5">
        {% include 'core/contact/partials/_form.html' with form=form %}
    </div>
{% endblock %}

core/templates/core/contact/partials/_form.html
<form id="contactForm" method="post" role="form">
    {% csrf_token %}
    {{ form.non_field_errors }}
    <div class="form-floating">
        {{ form.name }}
        {{ form.name.label_tag }}
        {{ form.name.errors }}
    </div>
    <div class="form-floating">
        {{ form.email }}
        {{ form.email.label_tag }}
        {{ form.email.errors }}
    </div>
    <div class="form-floating">
        {{ form.phone }}
        {{ form.phone.label_tag }}
        {{ form.phone.errors }}
    </div>
    <div class="form-floating">
        {{ form.subject }}
        {{ form.subject.label_tag }}
        {{ form.subject.errors }}
    </div>
    <div class="form-floating">
        {{ form.message }}
        {{ form.message.label_tag }}
        {{ form.message.errors }}
    </div>
    <br />
    <button class="btn btn-primary text-uppercase" id="submitButton" type="submit">Send</button>
</form>

core/templates/core/index.html
{% extends 'layout.html' %}

{% load i18n %}
{% load static %}

{% block title %}{{ APP_NAME }}{% endblock %}

{% block hero_title %}{{ APP_NAME }}{% endblock %}
{% block hero_subtitle %}{% translate 'A Blog Theme by Start Bootstrap' %}{% endblock %}
{% block hero_style %}style="background-image: url('{% static 'core/img/home-bg.jpg' %}')"{% endblock %}

{% block content %}
    {% for post in page_obj %}
        {% include 'blog/post/partials/_preview.html' with post=post %}
    {% endfor %}

    {% include 'partials/_pagination.html' %}
{% endblock %}

templates/base_layout.html
{% load i18n %}
{% load static %}

{% get_current_language as LANGUAGE_CODE %}

<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
<head>
    <title>{% block title %}{% endblock %} | Clean Blog</title>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}" />
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />

    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    {% block stylesheets %}{% endblock %}
</head>
<body>

    <!-- Font Awesome icons (free version)-->
    <script src="{% static 'js/fontawesome-6.3.0.min.js' %}"></script>
    <!-- Bootstrap core JS-->
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <!-- Core theme JS-->
    <script src="{% static 'js/scripts.js' %}"></script>
    {% block javascripts %}{% endblock %}
</body>
</html>

templates/layout.html
{% load i18n %}
{% load static %}

{% get_current_language as LANGUAGE_CODE %}

<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
<head>
    <title>{% block title %}{% endblock %} | Clean Blog</title>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}" />
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />

    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    <!-- Custom CSS -->
    <link href="{% static 'css/custom.css' %}" rel="stylesheet" />
    {% block stylesheets %}{% endblock %}
</head>
<body class="{% block body_class %}{% endblock %}">
    {% include 'partials/_nav.html' %}

    <!-- Page Header-->
    <header class="masthead" {% block hero_style %}{% endblock %}>
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="heading">
                        <h1>{% block hero_title %}{% endblock %}</h1>
                        <h2 class="subheading">{% block hero_subtitle %}{% endblock %}</h2>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <main role="main">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    {% include 'partials/_flash_messages.html' %}
                    {% block content %}{% endblock %}
                </div>
            </div>
        </div>
    </main>


    {% include 'partials/_footer.html' %}

    <!-- Font Awesome icons (free version)-->
    <script src="{% static 'js/fontawesome-6.3.0.min.js' %}"></script>
    <!-- Bootstrap core JS-->
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <!-- Core theme JS-->
    <script src="{% static 'js/scripts.js' %}"></script>
    {% block javascripts %}{% endblock %}
</body>
</html>

templates/partials/_flash_messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{% if message.tags %}{{ message.tags }}{% else %}info{% endif %} alert-dismissible"
             id="flash-message-alert">
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
            <strong>{{ message }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/partials/_footer.html
{% load i18n %}

<!-- Footer-->
<footer class="border-top">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <ul class="list-inline text-center">
                    <li class="list-inline-item">
                        <a href="#!">
                            <span class="fa-stack fa-lg">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#!">
                            <span class="fa-stack fa-lg">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#!">
                            <span class="fa-stack fa-lg">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                </ul>
                <div class="small text-center text-muted fst-italic">
                    {% now 'Y' as current_year %}
                    {% blocktranslate trimmed %}
                        Copyright &copy; {{ APP_NAME }} {{ current_year }}
                    {% endblocktranslate %}
                </div>
            </div>
        </div>
    </div>
</footer>

templates/partials/_nav.html
{% load i18n %}

<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="{% url 'home' %}">{{ APP_NAME }}</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="{% translate 'Toggle navigation' %}">
            {% translate 'Menu' %}
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ms-auto py-4 py-lg-0">
                <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'home' %}">{% translate 'Home' %}</a></li>
                <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'core:about' %}">{% translate 'About' %}</a></li>
                <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'core:contact' %}">{% translate 'Contact' %}</a></li>
                {% if user.is_authenticated %}
                    {% if user.is_staff %}
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'admin:index' %}">{% translate 'Admin' %}</a></li>
                    {% endif %}
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

templates/partials/_pagination.html
{% load i18n %}

<nav role="navigation" aria-labelledby="pagination-heading">
    <h4 id="pagination-heading" class="visually-hidden">{% translate 'Pagination' %}</h4>
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
            <li class="page-item" title="{% translate 'Go to previous page' %}">
                <a class="page-link text-uppercase" href="?page={{ page_obj.previous_page_number }}">{% translate '‹ Newest Posts' %}</a>
            </li>
        {% endif %}

        {% if page_obj.has_next %}
            <li class="page-item" title="{% translate 'Go to next page' %}">
                <a class="page-link text-uppercase" href="?page={{ page_obj.next_page_number }}">{% translate 'Older Posts ›' %}</a>
            </li>
        {% endif %}
    </ul>
</nav>